//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ControllersGame.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllersGame: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllersGame()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllersGame"",
    ""maps"": [
        {
            ""name"": ""PlayerControllers"",
            ""id"": ""17504c8f-3fd8-4cb0-a7e8-5940ed8b3a2b"",
            ""actions"": [
                {
                    ""name"": ""RUN"",
                    ""type"": ""Button"",
                    ""id"": ""fa5cf80a-fef0-44fb-be25-3d6087909de0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f82833ad-6482-4292-93f2-00119b5e4660"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RUN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControllers
        m_PlayerControllers = asset.FindActionMap("PlayerControllers", throwIfNotFound: true);
        m_PlayerControllers_RUN = m_PlayerControllers.FindAction("RUN", throwIfNotFound: true);
    }

    ~@ControllersGame()
    {
        UnityEngine.Debug.Assert(!m_PlayerControllers.enabled, "This will cause a leak and performance issues, ControllersGame.PlayerControllers.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControllers
    private readonly InputActionMap m_PlayerControllers;
    private List<IPlayerControllersActions> m_PlayerControllersActionsCallbackInterfaces = new List<IPlayerControllersActions>();
    private readonly InputAction m_PlayerControllers_RUN;
    public struct PlayerControllersActions
    {
        private @ControllersGame m_Wrapper;
        public PlayerControllersActions(@ControllersGame wrapper) { m_Wrapper = wrapper; }
        public InputAction @RUN => m_Wrapper.m_PlayerControllers_RUN;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControllers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllersActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControllersActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Add(instance);
            @RUN.started += instance.OnRUN;
            @RUN.performed += instance.OnRUN;
            @RUN.canceled += instance.OnRUN;
        }

        private void UnregisterCallbacks(IPlayerControllersActions instance)
        {
            @RUN.started -= instance.OnRUN;
            @RUN.performed -= instance.OnRUN;
            @RUN.canceled -= instance.OnRUN;
        }

        public void RemoveCallbacks(IPlayerControllersActions instance)
        {
            if (m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControllersActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControllersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControllersActions @PlayerControllers => new PlayerControllersActions(this);
    public interface IPlayerControllersActions
    {
        void OnRUN(InputAction.CallbackContext context);
    }
}
