//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ControllersGame.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllersGame: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllersGame()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllersGame"",
    ""maps"": [
        {
            ""name"": ""PlayerControllers"",
            ""id"": ""17504c8f-3fd8-4cb0-a7e8-5940ed8b3a2b"",
            ""actions"": [
                {
                    ""name"": ""WALKING"",
                    ""type"": ""Button"",
                    ""id"": ""fa5cf80a-fef0-44fb-be25-3d6087909de0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RUN"",
                    ""type"": ""Button"",
                    ""id"": ""302edd2e-d4d0-47d3-a9da-0a4f7cb5eee5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ATTACK"",
                    ""type"": ""Button"",
                    ""id"": ""1d1df7ba-b382-4d37-9689-9b76d1c7d829"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SHOOT"",
                    ""type"": ""Button"",
                    ""id"": ""dfa70385-67c5-4210-9bfe-529600dd3ae0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BACKWARDS"",
                    ""type"": ""Button"",
                    ""id"": ""94e03eff-f4a9-4053-9c6b-01433354781a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LEFT"",
                    ""type"": ""Button"",
                    ""id"": ""557c5e50-68a3-4173-ab6f-a551f2f3d209"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RIGHT"",
                    ""type"": ""Button"",
                    ""id"": ""3ccf41ae-78ae-43f2-997d-3cf093bba49d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f82833ad-6482-4292-93f2-00119b5e4660"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WALKING"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e3d66d7-8d4a-4ee2-8799-b602575eb904"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ATTACK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed6e30ac-463d-4343-8b1f-3550e22fac07"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RUN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b31f66ea-4b8e-4b0f-82cd-7f6445acee32"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHOOT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28adf8a6-5255-4da1-b949-109b2a2c4e57"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BACKWARDS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfbb9892-2162-43db-92ac-1d4497f4609e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36f88234-8b41-4f4e-90a3-25bc628a8c5b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControllers
        m_PlayerControllers = asset.FindActionMap("PlayerControllers", throwIfNotFound: true);
        m_PlayerControllers_WALKING = m_PlayerControllers.FindAction("WALKING", throwIfNotFound: true);
        m_PlayerControllers_RUN = m_PlayerControllers.FindAction("RUN", throwIfNotFound: true);
        m_PlayerControllers_ATTACK = m_PlayerControllers.FindAction("ATTACK", throwIfNotFound: true);
        m_PlayerControllers_SHOOT = m_PlayerControllers.FindAction("SHOOT", throwIfNotFound: true);
        m_PlayerControllers_BACKWARDS = m_PlayerControllers.FindAction("BACKWARDS", throwIfNotFound: true);
        m_PlayerControllers_LEFT = m_PlayerControllers.FindAction("LEFT", throwIfNotFound: true);
        m_PlayerControllers_RIGHT = m_PlayerControllers.FindAction("RIGHT", throwIfNotFound: true);
    }

    ~@ControllersGame()
    {
        UnityEngine.Debug.Assert(!m_PlayerControllers.enabled, "This will cause a leak and performance issues, ControllersGame.PlayerControllers.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControllers
    private readonly InputActionMap m_PlayerControllers;
    private List<IPlayerControllersActions> m_PlayerControllersActionsCallbackInterfaces = new List<IPlayerControllersActions>();
    private readonly InputAction m_PlayerControllers_WALKING;
    private readonly InputAction m_PlayerControllers_RUN;
    private readonly InputAction m_PlayerControllers_ATTACK;
    private readonly InputAction m_PlayerControllers_SHOOT;
    private readonly InputAction m_PlayerControllers_BACKWARDS;
    private readonly InputAction m_PlayerControllers_LEFT;
    private readonly InputAction m_PlayerControllers_RIGHT;
    public struct PlayerControllersActions
    {
        private @ControllersGame m_Wrapper;
        public PlayerControllersActions(@ControllersGame wrapper) { m_Wrapper = wrapper; }
        public InputAction @WALKING => m_Wrapper.m_PlayerControllers_WALKING;
        public InputAction @RUN => m_Wrapper.m_PlayerControllers_RUN;
        public InputAction @ATTACK => m_Wrapper.m_PlayerControllers_ATTACK;
        public InputAction @SHOOT => m_Wrapper.m_PlayerControllers_SHOOT;
        public InputAction @BACKWARDS => m_Wrapper.m_PlayerControllers_BACKWARDS;
        public InputAction @LEFT => m_Wrapper.m_PlayerControllers_LEFT;
        public InputAction @RIGHT => m_Wrapper.m_PlayerControllers_RIGHT;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControllers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllersActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControllersActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Add(instance);
            @WALKING.started += instance.OnWALKING;
            @WALKING.performed += instance.OnWALKING;
            @WALKING.canceled += instance.OnWALKING;
            @RUN.started += instance.OnRUN;
            @RUN.performed += instance.OnRUN;
            @RUN.canceled += instance.OnRUN;
            @ATTACK.started += instance.OnATTACK;
            @ATTACK.performed += instance.OnATTACK;
            @ATTACK.canceled += instance.OnATTACK;
            @SHOOT.started += instance.OnSHOOT;
            @SHOOT.performed += instance.OnSHOOT;
            @SHOOT.canceled += instance.OnSHOOT;
            @BACKWARDS.started += instance.OnBACKWARDS;
            @BACKWARDS.performed += instance.OnBACKWARDS;
            @BACKWARDS.canceled += instance.OnBACKWARDS;
            @LEFT.started += instance.OnLEFT;
            @LEFT.performed += instance.OnLEFT;
            @LEFT.canceled += instance.OnLEFT;
            @RIGHT.started += instance.OnRIGHT;
            @RIGHT.performed += instance.OnRIGHT;
            @RIGHT.canceled += instance.OnRIGHT;
        }

        private void UnregisterCallbacks(IPlayerControllersActions instance)
        {
            @WALKING.started -= instance.OnWALKING;
            @WALKING.performed -= instance.OnWALKING;
            @WALKING.canceled -= instance.OnWALKING;
            @RUN.started -= instance.OnRUN;
            @RUN.performed -= instance.OnRUN;
            @RUN.canceled -= instance.OnRUN;
            @ATTACK.started -= instance.OnATTACK;
            @ATTACK.performed -= instance.OnATTACK;
            @ATTACK.canceled -= instance.OnATTACK;
            @SHOOT.started -= instance.OnSHOOT;
            @SHOOT.performed -= instance.OnSHOOT;
            @SHOOT.canceled -= instance.OnSHOOT;
            @BACKWARDS.started -= instance.OnBACKWARDS;
            @BACKWARDS.performed -= instance.OnBACKWARDS;
            @BACKWARDS.canceled -= instance.OnBACKWARDS;
            @LEFT.started -= instance.OnLEFT;
            @LEFT.performed -= instance.OnLEFT;
            @LEFT.canceled -= instance.OnLEFT;
            @RIGHT.started -= instance.OnRIGHT;
            @RIGHT.performed -= instance.OnRIGHT;
            @RIGHT.canceled -= instance.OnRIGHT;
        }

        public void RemoveCallbacks(IPlayerControllersActions instance)
        {
            if (m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControllersActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControllersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControllersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControllersActions @PlayerControllers => new PlayerControllersActions(this);
    public interface IPlayerControllersActions
    {
        void OnWALKING(InputAction.CallbackContext context);
        void OnRUN(InputAction.CallbackContext context);
        void OnATTACK(InputAction.CallbackContext context);
        void OnSHOOT(InputAction.CallbackContext context);
        void OnBACKWARDS(InputAction.CallbackContext context);
        void OnLEFT(InputAction.CallbackContext context);
        void OnRIGHT(InputAction.CallbackContext context);
    }
}
